version: "3.7"

services:
  api:
    container_name: evolution_api
    image: evolution-api:2.3.6-fix
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - ZaperfyNet    # usa a mesma rede dos serviços existentes (redis e postgres)
    env_file:
      - .env
    expose:
      - 8080

volumes:
  evolution_instances:

networks:
  ZaperfyNet:
    external: true
